name: Deploy Front POS Comida

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project to deploy folder
        run: |
          rsync -av --delete ./ /docker/apps/front-pos-comida/

      - name: Deploy with Docker Compose
        run: |
          cd /docker/apps/front-pos-comida
          docker compose down
          docker compose up -d --build